version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  post_build:
    commands:
      - echo Fetching SSH key from Secrets Manager...
      - aws secretsmanager get-secret-value --secret-id ec2-ssh-key --query SecretString --output text > cicd.pem
      - chmod 400 cicd.pem

      - echo Deploying to EC2...
      - ssh -o StrictHostKeyChecking=no -i cicd.pem ubuntu@98.92.232.255 "cd ~/aws-cicd-demo && git pull && npm install && (pkill node || true) && nohup npm start > output.log 2>&1 < /dev/null &"
